#!/usr/bin/env bash
#
# Pin current vendor submodule versions.
# Creates or updates versions.lock with current commit hashes.
#
# Usage: ./scripts/pin-versions.sh [--verify]
#

set -euo pipefail

# Configuration
VENDOR_DIR="vendor"
VERSIONS_LOCK="versions.lock"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
VERIFY=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --verify)
            VERIFY=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--verify]"
            echo ""
            echo "Pin or verify vendor submodule versions."
            echo ""
            echo "Options:"
            echo "  --verify     Verify current versions match versions.lock"
            echo "  -h, --help   Show this help message"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Check we're in the right directory
if [[ ! -d "$VENDOR_DIR" ]]; then
    echo -e "${RED}Error: vendor directory not found. Run from project root.${NC}"
    exit 1
fi

# Known vendors
VENDORS=(
    "lastlayer"
    "piguard"
    "llmguard"
)

# Function to get current version of a vendor
get_version() {
    local name="$1"
    local path="$VENDOR_DIR/$name"

    if [[ -d "$path/.git" ]] || [[ -f "$path/.git" ]]; then
        (cd "$path" && git rev-parse HEAD 2>/dev/null) || echo "not-initialized"
    else
        echo "not-initialized"
    fi
}

# Verify mode
if [[ "$VERIFY" == "true" ]]; then
    echo "=== Verifying Vendor Versions ==="
    echo ""

    if [[ ! -f "$VERSIONS_LOCK" ]]; then
        echo -e "${RED}Error: $VERSIONS_LOCK not found${NC}"
        echo "Run '$0' (without --verify) to create it."
        exit 1
    fi

    mismatches=0

    while IFS='=' read -r name expected_version; do
        # Skip comments and empty lines
        [[ "$name" =~ ^#.*$ ]] && continue
        [[ -z "$name" ]] && continue

        current_version=$(get_version "$name")

        if [[ "$current_version" == "$expected_version" ]]; then
            echo -e "${GREEN}✓ $name: ${current_version:0:12}${NC}"
        else
            echo -e "${RED}✗ $name: expected ${expected_version:0:12}, got ${current_version:0:12}${NC}"
            ((mismatches++))
        fi
    done < "$VERSIONS_LOCK"

    echo ""
    if [[ $mismatches -eq 0 ]]; then
        echo -e "${GREEN}All versions match!${NC}"
        exit 0
    else
        echo -e "${RED}$mismatches version mismatch(es) found.${NC}"
        echo "Run './scripts/update-upstream.sh' or './scripts/pin-versions.sh' to fix."
        exit 1
    fi
fi

# Pin mode
echo "=== Pinning Vendor Versions ==="
echo ""

# Build lock file content
{
    echo "# Vendor submodule versions"
    echo "# Generated by pin-versions.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "#"
    echo "# To restore these versions:"
    echo "#   git submodule update --init"
    echo "#   ./scripts/pin-versions.sh --verify"
    echo ""

    for vendor in "${VENDORS[@]}"; do
        version=$(get_version "$vendor")
        echo "$vendor=$version"
        echo -e "  ${GREEN}$vendor: $version${NC}"
    done
} > "$VERSIONS_LOCK"

echo ""
echo -e "${GREEN}Versions pinned to $VERSIONS_LOCK${NC}"
echo ""
echo "To verify versions match: $0 --verify"
echo "To update to latest:      ./scripts/update-upstream.sh"
