#!/usr/bin/env bash
#
# Update all vendor submodules to their latest versions.
# Records updated versions to versions.lock for reproducibility.
#
# Usage: ./scripts/update-upstream.sh [--dry-run]
#

set -euo pipefail

# Configuration
VENDOR_DIR="vendor"
VERSIONS_LOCK="versions.lock"
DRY_RUN=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--dry-run]"
            echo ""
            echo "Update all vendor submodules to their latest versions."
            echo ""
            echo "Options:"
            echo "  --dry-run    Show what would be updated without making changes"
            echo "  -h, --help   Show this help message"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Check we're in the right directory
if [[ ! -d "$VENDOR_DIR" ]]; then
    echo -e "${RED}Error: vendor directory not found. Run from project root.${NC}"
    exit 1
fi

echo "=== Updating Vendor Submodules ==="
echo ""

# Initialize submodules if needed
if [[ ! -f .gitmodules ]]; then
    echo -e "${YELLOW}No .gitmodules found. Setting up submodules...${NC}"
    if [[ "$DRY_RUN" == "false" ]]; then
        # Create .gitmodules if needed
        touch .gitmodules
    fi
fi

# Function to update a submodule
update_submodule() {
    local name="$1"
    local path="$VENDOR_DIR/$name"

    echo -e "${YELLOW}Checking $name...${NC}"

    if [[ ! -d "$path" ]]; then
        echo -e "  ${YELLOW}Submodule not initialized, skipping${NC}"
        return 0
    fi

    # Get current commit
    local current_commit
    current_commit=$(cd "$path" && git rev-parse HEAD 2>/dev/null || echo "unknown")

    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "  Current: ${current_commit:0:8}"
        echo -e "  ${YELLOW}[DRY RUN] Would fetch and update to latest${NC}"
        return 0
    fi

    # Fetch latest
    (cd "$path" && git fetch origin 2>/dev/null) || {
        echo -e "  ${RED}Failed to fetch, skipping${NC}"
        return 0
    }

    # Get latest main/master commit
    local latest_commit
    latest_commit=$(cd "$path" && git rev-parse origin/main 2>/dev/null || git rev-parse origin/master 2>/dev/null || echo "unknown")

    if [[ "$current_commit" == "$latest_commit" ]]; then
        echo -e "  ${GREEN}Already up to date: ${current_commit:0:8}${NC}"
    else
        echo -e "  Current: ${current_commit:0:8}"
        echo -e "  Latest:  ${latest_commit:0:8}"

        # Update to latest
        (cd "$path" && git checkout "$latest_commit") || {
            echo -e "  ${RED}Failed to checkout latest${NC}"
            return 1
        }
        echo -e "  ${GREEN}Updated to ${latest_commit:0:8}${NC}"
    fi
}

# Update known vendor submodules
VENDORS=(
    "lastlayer"
    "piguard"
    "llmguard"
)

for vendor in "${VENDORS[@]}"; do
    update_submodule "$vendor"
    echo ""
done

# Record versions to lock file
if [[ "$DRY_RUN" == "false" ]]; then
    echo "=== Recording versions to $VERSIONS_LOCK ==="
    {
        echo "# Vendor submodule versions"
        echo "# Generated by update-upstream.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo ""

        for vendor in "${VENDORS[@]}"; do
            path="$VENDOR_DIR/$vendor"
            if [[ -d "$path" ]]; then
                commit=$(cd "$path" && git rev-parse HEAD 2>/dev/null || echo "not-initialized")
                echo "$vendor=$commit"
            else
                echo "$vendor=not-initialized"
            fi
        done
    } > "$VERSIONS_LOCK"

    echo -e "${GREEN}Versions recorded to $VERSIONS_LOCK${NC}"
else
    echo -e "${YELLOW}[DRY RUN] Would record versions to $VERSIONS_LOCK${NC}"
fi

echo ""
echo "=== Update Complete ==="

# Show summary
if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}This was a dry run. No changes were made.${NC}"
else
    echo "Run 'git status' to see changes."
    echo "Commit changes with: git add vendor $VERSIONS_LOCK && git commit -m 'chore: update vendor submodules'"
fi
